name: Stack

on:
  push:
  pull_request:

jobs:
  build:
    name: Stack CI - Linux - ${{ matrix.resolver }} - ${{ matrix.yaml }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - resolver: lts-12
            ghc: 8.4.4
            yaml: stack.yaml
          - resolver: lts-12
            ghc: 8.4.4
            yaml: stack-master.yaml
          - resolver: lts-14
            ghc: 8.6.5
            yaml: stack-master.yaml
          - resolver: lts-16
            ghc: 8.8.4
            yaml: stack-master.yaml
          - resolver: lts-18
            ghc: 8.10.7
            yaml: stack-master.yaml
          - resolver: lts-19
            ghc: 9.0.2
            yaml: stack.yaml
          - resolver: lts-19
            ghc: 9.0.2
            yaml: stack-master.yaml

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Prepare apt sources
        run: |
          set -ex
          sudo add-apt-repository -y ppa:hvr/ghc
          sudo apt update -y

      - name: Install C dependencies
        run: |
          set -ex
          sudo apt install -y \
            libx11-dev \
            libxext-dev \
            libxft-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxss-dev \
            #

      - name: Install GHC
        # use system ghc (if available) in stack, don't waste GH Actions cache space
        continue-on-error: true
        run: |
          set -ex
          sudo apt install -y ghc-${{ matrix.ghc }}
          echo /opt/ghc/${{ matrix.ghc }}/bin >> $GITHUB_PATH

      - name: Refresh caches once a month
        id: cache-date
        # GHA writes caches on the first miss and then never updates them again;
        # force updating the cache at least once a month. Additionally, the
        # date is prefixed with an epoch number to let us manually refresh the
        # cache when needed. This is a workaround for https://github.com/actions/cache/issues/2
        run: |
          echo "::set-output name=date::1-$(date +%Y-%m)"

      - name: Cache Haskell package metadata
        uses: actions/cache@v2
        with:
          path: ~/.stack/pantry
          key: stack-pantry-${{ runner.os }}-${{ steps.cache-date.outputs.date }}

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack/*
            !~/.stack/pantry
            !~/.stack/programs
          key: stack-${{ runner.os }}-${{ matrix.resolver }}-${{ steps.cache-date.outputs.date }}-${{ hashFiles(matrix.yaml) }}-${{ hashFiles('*.cabal') }}
          restore-keys: |
            stack-${{ runner.os }}-${{ matrix.resolver }}-${{ steps.cache-date.outputs.date }}-${{ hashFiles(matrix.yaml) }}-
            stack-${{ runner.os }}-${{ matrix.resolver }}-${{ steps.cache-date.outputs.date }}-

      - name: Update hackage index
        # always update index to prevent the shared ~/.stack/pantry cache from being empty
        run: |
          set -ex
          stack update

      - name: Build and test
        run: |
          set -ex

          # workaround for stack/pantry caching of github archives
          sed -e "s/@{today}/@{$(date -u --iso-8601=seconds)}/" -i ${{ matrix.yaml }}

          stack test \
            --fast --no-terminal \
            --stack-yaml=${{ matrix.yaml }} \
            --resolver=${{ matrix.resolver }} --system-ghc \
            --flag=xmonad-contrib:pedantic
